compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

checksumBehavior: throw

enableImmutableInstalls: true

enableInlineBuilds: true

logFilters:
  - code: YN0004
    level: discard
  - code: YN0061
    level: discard

networkConcurrency: 8

nodeLinker: node-modules

npmScopes:
  geniusventures:
    npmRegistryServer: "https://registry.npmjs.org"
  gnus:
    npmRegistryServer: "https://registry.npmjs.org"
