checksumBehavior: throw

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableInlineBuilds: true

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0061
    level: discard
  - code: YN0060
    level: discard

packageExtensions:
  "eslint-config-next@*":
    peerDependencies:
      eslint: "^7.23.0 || ^8.0.0 || ^9.0.0"

networkConcurrency: 8

nodeLinker: node-modules

npmScopes:
  geniusventures:
    npmRegistryServer: "https://registry.npmjs.org"
  gnus:
    npmRegistryServer: "https://registry.npmjs.org"
