checksumBehavior: throw

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: true

enableInlineBuilds: true

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0061
    level: discard

networkConcurrency: 8

nodeLinker: node-modules

npmScopes:
  geniusventures:
    npmRegistryServer: "https://registry.npmjs.org"
  gnus:
    npmRegistryServer: "https://registry.npmjs.org"
