/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
	BaseContract,
	BigNumberish,
	BytesLike,
	FunctionFragment,
	Result,
	Interface,
	EventFragment,
	AddressLike,
	ContractRunner,
	ContractMethod,
	Listener,
} from 'ethers';
import type {
	TypedContractEvent,
	TypedDeferredTopicFilter,
	TypedEventLog,
	TypedLogDescription,
	TypedListener,
	TypedContractMethod,
} from './common';

export declare namespace IDiamondCut {
	export type FacetCutStruct = {
		facetAddress: AddressLike;
		action: BigNumberish;
		functionSelectors: BytesLike[];
	};

	export type FacetCutStructOutput = [
		facetAddress: string,
		action: bigint,
		functionSelectors: string[],
	] & { facetAddress: string; action: bigint; functionSelectors: string[] };
}

export declare namespace IDiamondLoupe {
	export type FacetStruct = {
		facetAddress: AddressLike;
		functionSelectors: BytesLike[];
	};

	export type FacetStructOutput = [facetAddress: string, functionSelectors: string[]] & {
		facetAddress: string;
		functionSelectors: string[];
	};
}

export interface GNUSDAODiamondInterface extends Interface {
	getFunction(
		nameOrSignature:
			| 'DEFAULT_ADMIN_ROLE'
			| 'diamondCut'
			| 'diamondInitialize000'
			| 'facetAddress'
			| 'facetAddresses'
			| 'facetFunctionSelectors'
			| 'facets'
			| 'getRoleAdmin'
			| 'getRoleMember'
			| 'getRoleMemberCount'
			| 'grantRole'
			| 'hasRole'
			| 'owner'
			| 'renounceRole'
			| 'revokeRole'
			| 'supportsInterface'
			| 'transferOwnership'
			| 'UPGRADER_ROLE',
	): FunctionFragment;

	getEvent(
		nameOrSignatureOrTopic:
			| 'DiamondCut'
			| 'InitLog'
			| 'OwnershipTransferred'
			| 'RoleAdminChanged'
			| 'RoleGranted'
			| 'RoleRevoked',
	): EventFragment;

	encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
	encodeFunctionData(
		functionFragment: 'diamondCut',
		values: [IDiamondCut.FacetCutStruct[], AddressLike, BytesLike],
	): string;
	encodeFunctionData(functionFragment: 'diamondInitialize000', values?: undefined): string;
	encodeFunctionData(functionFragment: 'facetAddress', values: [BytesLike]): string;
	encodeFunctionData(functionFragment: 'facetAddresses', values?: undefined): string;
	encodeFunctionData(
		functionFragment: 'facetFunctionSelectors',
		values: [AddressLike],
	): string;
	encodeFunctionData(functionFragment: 'facets', values?: undefined): string;
	encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
	encodeFunctionData(
		functionFragment: 'getRoleMember',
		values: [BytesLike, BigNumberish],
	): string;
	encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string;
	encodeFunctionData(
		functionFragment: 'grantRole',
		values: [BytesLike, AddressLike],
	): string;
	encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
	encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
	encodeFunctionData(
		functionFragment: 'renounceRole',
		values: [BytesLike, AddressLike],
	): string;
	encodeFunctionData(
		functionFragment: 'revokeRole',
		values: [BytesLike, AddressLike],
	): string;
	encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
	encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
	encodeFunctionData(functionFragment: 'UPGRADER_ROLE', values?: undefined): string;

	decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'diamondCut', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'diamondInitialize000', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'facetAddress', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'facetAddresses', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'facetFunctionSelectors', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'facets', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'UPGRADER_ROLE', data: BytesLike): Result;
}

export namespace DiamondCutEvent {
	export type InputTuple = [
		_diamondCut: IDiamondCut.FacetCutStruct[],
		_init: AddressLike,
		_calldata: BytesLike,
	];
	export type OutputTuple = [
		_diamondCut: IDiamondCut.FacetCutStructOutput[],
		_init: string,
		_calldata: string,
	];
	export interface OutputObject {
		_diamondCut: IDiamondCut.FacetCutStructOutput[];
		_init: string;
		_calldata: string;
	}
	export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
	export type Filter = TypedDeferredTopicFilter<Event>;
	export type Log = TypedEventLog<Event>;
	export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitLogEvent {
	export type InputTuple = [sender: AddressLike, initializer: string];
	export type OutputTuple = [sender: string, initializer: string];
	export interface OutputObject {
		sender: string;
		initializer: string;
	}
	export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
	export type Filter = TypedDeferredTopicFilter<Event>;
	export type Log = TypedEventLog<Event>;
	export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
	export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
	export type OutputTuple = [previousOwner: string, newOwner: string];
	export interface OutputObject {
		previousOwner: string;
		newOwner: string;
	}
	export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
	export type Filter = TypedDeferredTopicFilter<Event>;
	export type Log = TypedEventLog<Event>;
	export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
	export type InputTuple = [
		role: BytesLike,
		previousAdminRole: BytesLike,
		newAdminRole: BytesLike,
	];
	export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
	export interface OutputObject {
		role: string;
		previousAdminRole: string;
		newAdminRole: string;
	}
	export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
	export type Filter = TypedDeferredTopicFilter<Event>;
	export type Log = TypedEventLog<Event>;
	export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
	export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
	export type OutputTuple = [role: string, account: string, sender: string];
	export interface OutputObject {
		role: string;
		account: string;
		sender: string;
	}
	export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
	export type Filter = TypedDeferredTopicFilter<Event>;
	export type Log = TypedEventLog<Event>;
	export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
	export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
	export type OutputTuple = [role: string, account: string, sender: string];
	export interface OutputObject {
		role: string;
		account: string;
		sender: string;
	}
	export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
	export type Filter = TypedDeferredTopicFilter<Event>;
	export type Log = TypedEventLog<Event>;
	export type LogDescription = TypedLogDescription<Event>;
}

export interface GNUSDAODiamond extends BaseContract {
	connect(runner?: ContractRunner | null): GNUSDAODiamond;
	waitForDeployment(): Promise<this>;

	interface: GNUSDAODiamondInterface;

	queryFilter<TCEvent extends TypedContractEvent>(
		event: TCEvent,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined,
	): Promise<Array<TypedEventLog<TCEvent>>>;
	queryFilter<TCEvent extends TypedContractEvent>(
		filter: TypedDeferredTopicFilter<TCEvent>,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined,
	): Promise<Array<TypedEventLog<TCEvent>>>;

	on<TCEvent extends TypedContractEvent>(
		event: TCEvent,
		listener: TypedListener<TCEvent>,
	): Promise<this>;
	on<TCEvent extends TypedContractEvent>(
		filter: TypedDeferredTopicFilter<TCEvent>,
		listener: TypedListener<TCEvent>,
	): Promise<this>;

	once<TCEvent extends TypedContractEvent>(
		event: TCEvent,
		listener: TypedListener<TCEvent>,
	): Promise<this>;
	once<TCEvent extends TypedContractEvent>(
		filter: TypedDeferredTopicFilter<TCEvent>,
		listener: TypedListener<TCEvent>,
	): Promise<this>;

	listeners<TCEvent extends TypedContractEvent>(
		event: TCEvent,
	): Promise<Array<TypedListener<TCEvent>>>;
	listeners(eventName?: string): Promise<Array<Listener>>;
	removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

	DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], 'view'>;

	diamondCut: TypedContractMethod<
		[_diamondCut: IDiamondCut.FacetCutStruct[], _init: AddressLike, _calldata: BytesLike],
		[void],
		'nonpayable'
	>;

	diamondInitialize000: TypedContractMethod<[], [void], 'nonpayable'>;

	facetAddress: TypedContractMethod<[_functionSelector: BytesLike], [string], 'view'>;

	facetAddresses: TypedContractMethod<[], [string[]], 'view'>;

	facetFunctionSelectors: TypedContractMethod<[_facet: AddressLike], [string[]], 'view'>;

	facets: TypedContractMethod<[], [IDiamondLoupe.FacetStructOutput[]], 'view'>;

	getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], 'view'>;

	getRoleMember: TypedContractMethod<
		[role: BytesLike, index: BigNumberish],
		[string],
		'view'
	>;

	getRoleMemberCount: TypedContractMethod<[role: BytesLike], [bigint], 'view'>;

	grantRole: TypedContractMethod<
		[role: BytesLike, account: AddressLike],
		[void],
		'nonpayable'
	>;

	hasRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], 'view'>;

	owner: TypedContractMethod<[], [string], 'view'>;

	renounceRole: TypedContractMethod<
		[role: BytesLike, account: AddressLike],
		[void],
		'nonpayable'
	>;

	revokeRole: TypedContractMethod<
		[role: BytesLike, account: AddressLike],
		[void],
		'nonpayable'
	>;

	supportsInterface: TypedContractMethod<[_interfaceId: BytesLike], [boolean], 'view'>;

	transferOwnership: TypedContractMethod<[_newOwner: AddressLike], [void], 'nonpayable'>;

	UPGRADER_ROLE: TypedContractMethod<[], [string], 'view'>;

	getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

	getFunction(
		nameOrSignature: 'DEFAULT_ADMIN_ROLE',
	): TypedContractMethod<[], [string], 'view'>;
	getFunction(
		nameOrSignature: 'diamondCut',
	): TypedContractMethod<
		[_diamondCut: IDiamondCut.FacetCutStruct[], _init: AddressLike, _calldata: BytesLike],
		[void],
		'nonpayable'
	>;
	getFunction(
		nameOrSignature: 'diamondInitialize000',
	): TypedContractMethod<[], [void], 'nonpayable'>;
	getFunction(
		nameOrSignature: 'facetAddress',
	): TypedContractMethod<[_functionSelector: BytesLike], [string], 'view'>;
	getFunction(
		nameOrSignature: 'facetAddresses',
	): TypedContractMethod<[], [string[]], 'view'>;
	getFunction(
		nameOrSignature: 'facetFunctionSelectors',
	): TypedContractMethod<[_facet: AddressLike], [string[]], 'view'>;
	getFunction(
		nameOrSignature: 'facets',
	): TypedContractMethod<[], [IDiamondLoupe.FacetStructOutput[]], 'view'>;
	getFunction(
		nameOrSignature: 'getRoleAdmin',
	): TypedContractMethod<[role: BytesLike], [string], 'view'>;
	getFunction(
		nameOrSignature: 'getRoleMember',
	): TypedContractMethod<[role: BytesLike, index: BigNumberish], [string], 'view'>;
	getFunction(
		nameOrSignature: 'getRoleMemberCount',
	): TypedContractMethod<[role: BytesLike], [bigint], 'view'>;
	getFunction(
		nameOrSignature: 'grantRole',
	): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
	getFunction(
		nameOrSignature: 'hasRole',
	): TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], 'view'>;
	getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
	getFunction(
		nameOrSignature: 'renounceRole',
	): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
	getFunction(
		nameOrSignature: 'revokeRole',
	): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
	getFunction(
		nameOrSignature: 'supportsInterface',
	): TypedContractMethod<[_interfaceId: BytesLike], [boolean], 'view'>;
	getFunction(
		nameOrSignature: 'transferOwnership',
	): TypedContractMethod<[_newOwner: AddressLike], [void], 'nonpayable'>;
	getFunction(nameOrSignature: 'UPGRADER_ROLE'): TypedContractMethod<[], [string], 'view'>;

	getEvent(
		key: 'DiamondCut',
	): TypedContractEvent<
		DiamondCutEvent.InputTuple,
		DiamondCutEvent.OutputTuple,
		DiamondCutEvent.OutputObject
	>;
	getEvent(
		key: 'InitLog',
	): TypedContractEvent<
		InitLogEvent.InputTuple,
		InitLogEvent.OutputTuple,
		InitLogEvent.OutputObject
	>;
	getEvent(
		key: 'OwnershipTransferred',
	): TypedContractEvent<
		OwnershipTransferredEvent.InputTuple,
		OwnershipTransferredEvent.OutputTuple,
		OwnershipTransferredEvent.OutputObject
	>;
	getEvent(
		key: 'RoleAdminChanged',
	): TypedContractEvent<
		RoleAdminChangedEvent.InputTuple,
		RoleAdminChangedEvent.OutputTuple,
		RoleAdminChangedEvent.OutputObject
	>;
	getEvent(
		key: 'RoleGranted',
	): TypedContractEvent<
		RoleGrantedEvent.InputTuple,
		RoleGrantedEvent.OutputTuple,
		RoleGrantedEvent.OutputObject
	>;
	getEvent(
		key: 'RoleRevoked',
	): TypedContractEvent<
		RoleRevokedEvent.InputTuple,
		RoleRevokedEvent.OutputTuple,
		RoleRevokedEvent.OutputObject
	>;

	filters: {
		'DiamondCut(tuple[],address,bytes)': TypedContractEvent<
			DiamondCutEvent.InputTuple,
			DiamondCutEvent.OutputTuple,
			DiamondCutEvent.OutputObject
		>;
		DiamondCut: TypedContractEvent<
			DiamondCutEvent.InputTuple,
			DiamondCutEvent.OutputTuple,
			DiamondCutEvent.OutputObject
		>;

		'InitLog(address,string)': TypedContractEvent<
			InitLogEvent.InputTuple,
			InitLogEvent.OutputTuple,
			InitLogEvent.OutputObject
		>;
		InitLog: TypedContractEvent<
			InitLogEvent.InputTuple,
			InitLogEvent.OutputTuple,
			InitLogEvent.OutputObject
		>;

		'OwnershipTransferred(address,address)': TypedContractEvent<
			OwnershipTransferredEvent.InputTuple,
			OwnershipTransferredEvent.OutputTuple,
			OwnershipTransferredEvent.OutputObject
		>;
		OwnershipTransferred: TypedContractEvent<
			OwnershipTransferredEvent.InputTuple,
			OwnershipTransferredEvent.OutputTuple,
			OwnershipTransferredEvent.OutputObject
		>;

		'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<
			RoleAdminChangedEvent.InputTuple,
			RoleAdminChangedEvent.OutputTuple,
			RoleAdminChangedEvent.OutputObject
		>;
		RoleAdminChanged: TypedContractEvent<
			RoleAdminChangedEvent.InputTuple,
			RoleAdminChangedEvent.OutputTuple,
			RoleAdminChangedEvent.OutputObject
		>;

		'RoleGranted(bytes32,address,address)': TypedContractEvent<
			RoleGrantedEvent.InputTuple,
			RoleGrantedEvent.OutputTuple,
			RoleGrantedEvent.OutputObject
		>;
		RoleGranted: TypedContractEvent<
			RoleGrantedEvent.InputTuple,
			RoleGrantedEvent.OutputTuple,
			RoleGrantedEvent.OutputObject
		>;

		'RoleRevoked(bytes32,address,address)': TypedContractEvent<
			RoleRevokedEvent.InputTuple,
			RoleRevokedEvent.OutputTuple,
			RoleRevokedEvent.OutputObject
		>;
		RoleRevoked: TypedContractEvent<
			RoleRevokedEvent.InputTuple,
			RoleRevokedEvent.OutputTuple,
			RoleRevokedEvent.OutputObject
		>;
	};
}
