/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GNUSDAODiamond } from './GNUSDAODiamond';
export * as factories from './factories';
export { GNUSDAODiamond__factory } from './factories/GNUSDAODiamond__factory';
